import { WarehouseInventory, StoreInventory } from "./Inventory";

console.log("=== Exercício 2 - Inventário de Itens ===\n");
console.log("--- ARMAZÉM ---");
const warehouse = new WarehouseInventory();
warehouse.addItem("Notebook", 100);
warehouse.addItem("Mouse", 250);
warehouse.addItem("Teclado", 150);
warehouse.addItem("Monitor", 80);
warehouse.addItem("Notebook", 50);
warehouse.displayInventory();
console.log("\n--- Removendo item ---");
warehouse.removeItem("Mouse");
warehouse.displayInventory();
console.log("\n--- Tentando remover item inexistente ---");
warehouse.removeItem("Webcam");
console.log("\n--- Inventário completo (objeto) ---");
console.log(warehouse.getInventory());
console.log("\n" + "=".repeat(50));
console.log("\n--- LOJA ---");
const store = new StoreInventory();
store.addItem("Caneta", 5);
store.addItem("Caderno", 8);
store.addItem("Lápis", 10);
store.addItem("Borracha", 3);
store.displayInventory();
console.log("\n--- Tentando adicionar mais unidades ---");
store.addItem("Caneta", 3);
store.addItem("Lápis", 5);
store.displayInventory();
console.log("\n--- Tentando ultrapassar o limite ---");
store.addItem("Caderno", 5);
console.log("\n--- Adicionando novo item no limite ---");
store.addItem("Régua", 10);
store.displayInventory();
console.log("\n--- Inventário completo da loja (objeto) ---");
console.log(store.getInventory());
