import { Election, Poll } from "./VoteSystem";

console.log("=== Exercício 4 - Sistema de Votação ===\n");
console.log("--- ELEIÇÃO MUNICIPAL ---");
const election = new Election();
election.voteFor("João Silva");
election.voteFor("Maria Santos");
election.voteFor("Pedro Costa");
election.voteFor("João Silva");
election.voteFor("Maria Santos");
election.voteFor("João Silva");
election.voteFor("Ana Paula");
election.voteFor("Pedro Costa");
election.voteFor("João Silva");
election.voteFor("Maria Santos");
election.voteFor("Ana Paula");
election.voteFor("João Silva");
election.displayResults();
console.log("\n--- Objeto de resultados retornado ---");
console.log(election.getResults());
console.log("\n" + "=".repeat(50));
console.log("\n--- ENQUETE: MELHOR LINGUAGEM DE PROGRAMAÇÃO ---");
const poll = new Poll();
poll.voteFor("JavaScript");
poll.voteFor("Python");
poll.voteFor("TypeScript");
poll.voteFor("Python");
poll.voteFor("JavaScript");
poll.voteFor("Java");
poll.voteFor("Python");
poll.voteFor("TypeScript");
poll.voteFor("Python");
poll.voteFor("JavaScript");
poll.voteFor("Python");
poll.voteFor("C#");
poll.voteFor("Python");
poll.voteFor("TypeScript");
poll.voteFor("JavaScript");
poll.displayResults();
console.log("\n--- Array de resultados ordenados retornado ---");
console.log(poll.getResults());
console.log("\n" + "=".repeat(50));
console.log("\n--- ENQUETE: MELHOR FILME DE 2024 ---");
const moviePoll = new Poll();
moviePoll.voteFor("Oppenheimer");
moviePoll.voteFor("Barbie");
moviePoll.voteFor("Duna: Parte 2");
moviePoll.voteFor("Oppenheimer");
moviePoll.voteFor("Oppenheimer");
moviePoll.voteFor("Barbie");
moviePoll.voteFor("Duna: Parte 2");
moviePoll.voteFor("Oppenheimer");
moviePoll.voteFor("Killers of the Flower Moon");
moviePoll.voteFor("Duna: Parte 2");
moviePoll.displayResults();
